nome: Gerar dados

on:
em:
  Horário: # Executar a cada 12 horas
    - cron: "* */12 * *  *"
  workflow_dispatch:

Vagas:
  construir:
    name: Trabalhos para atualizar dados
    Runs-on: ubuntu-mais recente
    Passos:
      # Animação Snake
      - usos: Platane/snk@master
        Identificação: Snake-gif
        com:
          github_user_name: Dumonster27
          svg_out_path: dist/github-contribution-grid-snake.svg

      - Usos: Crazy-Max/Ghaction-GitHub-pages@v2.1.3
        with:
          target_branch: saída
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ segredos. GITHUB_TOKEN }}
